### ISSUE TITLE
Question about how tracks are updated

### ISSUE THREAD

**Issue by ghost** [jamesfairhurst/smart-playlists-for-spotify#19]
When I log in and the message appears that my tracks are updated from Spotify, does that mean that the playlists are also modified with new and removed tracks, or is a delete/recreate required?

If they are automatically updated, is a simple push to Spotify required to update the tracks in the actual Spotify playlists or must we delete the playlists on Spotify and push new?

Thanks for this extremely useful tool!

**Comment by jamesfairhurst** [comment]
Hey, sorry for the slow response. No it just means that any new tracks since the last time you visited have been downloaded. You don't need to delete and recreate the playlist though - just click the "Push to Spotify" and it'll update the existing one.

Do have plans to have a "live" playlist where it'll update automatically depending on the rules but need to find time for it!
